name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
    
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependency package-lock
        run:
          npm install --package-lock-only
      - name: Install dependency npm
        run:          
          npm ci
      - name: Uninstall Playwright
        run: npm uninstall playwright
      - name: Install Playwright npm test package
        run: npm install -D @playwright/test
      - name: Install Playwright Chromium browser only
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
